### ISSUE TITLE
Upgrade to the latest Airflow

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-keeper#15]
Upgrade to the latest version of Airflow

**Comment by shreyaspapi** [comment]
I will try this.

**Comment by shreyaspapi** [comment]
> I will try this.

BTW, I tried this, updated the `AIRFLOW` to latest stable version `2.2.3`. Even thou I am familiar with docker I am not sure any other things to change, can you help me with the installation or upgrade docs for `AIRFLOW`?

**Comment by mikeghen** [comment]
I dont think this involves much more than that, did you verify the versions upgraded when you deploy?

**Comment by shreyaspapi** [comment]
> I dont think this involves much more than that, did you verify the versions upgraded when you deploy?

Yup I did I will create a PR.

**Comment by MrSquiggles13** [comment]
@shreyaspapi is this finished? Can you post the PR

**Comment by shreyaspapi** [comment]
Nope I didn't get the time, @MrSquiggles13 you can take this issue. You will need to run the keeper locally and test, if it works on the latest `airflow`.

**Comment by MrSquiggles13** [comment]
@shreyaspapi im not really familiar with this technology but i can do some research and give it a go

**Comment by samirsalem** [comment]
This has been resolved, the PR has been merged https://github.com/Ricochet-Exchange/ricochet-keeper/pull/25
