### ISSUE TITLE
Make new Docker Image

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-keeper#18]
Keepers have been using my tellor-airflow image but we need to incorporate a docker image here and build it without relying on the one I pushed to docker hub months age.

This issue is to make a Dockerfile to use instead of my dockerhub image. A docker file for this can be found here: https://github.com/tellor-io/airflow

**Comment by samirsalem** [comment]
This has been resolved, the PR has been merged https://github.com/Ricochet-Exchange/ricochet-keeper/pull/25
