### ISSUE TITLE
Move all constants to dedicated class

### ISSUE THREAD

**Issue by nikramakrishnan** [Ricochet-Exchange/ricochet-keeper#23]
Issue inspired from [discussion](https://github.com/Ricochet-Exchange/ricochet-keeper/pull/22#discussion_r789705568) on #22.

**Comment by nikramakrishnan** [comment]
I'd like to take this.

**Comment by mikeghen** [comment]
@nikramakrishnan have at it, I tied a bounty to it

**Comment by mikeghen** [comment]
all set @nikramakrishnan
